# SPDX-License-Identifier: Apache-2.0
version: '2.1'

volumes:
  pgdata:

networks:
  network.com:
    external:
      name: net_test

services:
  refinerdb.network.com:
    image: fujitsu/refinerdb:latest
    container_name: refinerdb
    hostname: refinerdb.network.com
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    # ports:
    #   - 5432:5432
    networks:
      - network.com

  refiner.network.com:
    image: fujitsu/refiner:latest
    container_name: refiner
    hostname: refiner.network.com
    volumes:
      - ./config/config.ini:/opt/config/config.ini
      - ./config/connection-config-docker.yaml:/opt/config/connection-config.yaml
      - /home/atsushi/dev/hyperledger/Ledger-Data-Refiner/log:/root/refiner/log
      - /home/atsushi/dev/hyperledger/fabric-samples/test-network/organizations:/opt/organizations
    command: sh -c "/opt/ledgerdata-refiner"
    ports:
      - 30052:30052
    depends_on:
      refinerdb.network.com:
        condition: service_healthy
    networks:
      - network.com